feature(commit): TRACEFOSS-1007 update docs and fix regex

diff --git a/dev/commit-msg b/dev/commit-msg
--- a/dev/commit-msg
+++ b/dev/commit-msg
@@ -1,23 +1,21 @@
 #!/usr/bin/env bash
 
-if [ -z "$1" ]; then
-	echo "Missing argument (commit message). Did you try to run this manually?"
+if [ ! -e "$1" ]; then
+	echo "Argument for the commit message file is missing or the file \"$1\" does not exist. Did you try to run this manually?"
 	exit 1
 fi
 
-commitTitle="$(cat $1 | head -n1)"
+commitTitle="$(cat "$1" | head -n1)"
 
-# ignore merge requests
-if echo "$commitTitle" | grep -qE "^Merge branch '.*"; then
-	echo "Commit hook: ignoring branch merge"
+if echo "${commitTitle}" | grep -qE "^Merge branch '.*"; then
+	echo "Commit hook: ignoring merge commit."
 	exit 0
 fi
 
-url="$(git remote get-url origin | sed 's/\.git/#commit-messages/')"
+export EXPRESSION='^(chore|fix|feature)(\([A-Za-z0-9\/-]+\))?: [A-Z0-9-]+ .+$'
 
-# check semantic versioning scheme
-if ! echo "$commitTitle" | grep -qE '^(chore|fix|feat)\([a-z0-9\/-]+\)\s?:\s?[A-Z0-9-]+.*$'; then
-	echo "Your commit title did not follow commit rules: $commitTitle"
-	echo "Please see .git/hooks/commit-msg"
+if ! echo "${commitTitle}" | grep -qE "${EXPRESSION}"; then
+	echo "Your commit title \"${commitTitle}\" does not follow the commit rules."
+	echo "It has to match \"${EXPRESSION}\"."
 	exit 1
 fi
